### ISSUE TITLE
第一次进入for循环的时候，下边代码的两个if应该都会进入。

### ISSUE THREAD

**Issue by kimti** [songbaoming/DouDiZhu#2]
int begin = 0;
			for (auto mem : selection.group){
				if (!begin)
					begin = mem.first;
				if (begin++ != mem.first || mem.first >= 15)//牌不是连续的或者带了2及以上的牌
					return;
			}

**Comment by songbaoming** [comment]
是的，当时设计如此。可以更改逻辑，给变量 begin 赋初值为 selection.group.begin().first，然后去掉循环内第一个判断语句，以减少循环内判断次数。
