### ISSUE TITLE
DivideIntoGroups 里 查找单顺 这个for 不会走

### ISSUE THREAD

**Issue by bytehello** [songbaoming/DouDiZhu#5]
`if (begin - 1 != b->first)
--p;`
这个判断在 n == 5的时候才会走到，n == 5 必定是 走的++n ，走++n 的话 begin == b->first 必定成立，那么这个判断岂不是多此一举？

**Comment by songbaoming** [comment]
你说的对，这个判断没有必要，需要去掉。
